#!/bin/bash
cd ~/eprom

>logs/conn.log

# Terminar proceso de otra instancia del script si existe
script_name=${BASH_SOURCE[0]}
for pid in $(pidof -x $script_name); do
    if [ $pid != $$ ]; then
        kill $pid
		echo $(date) - Reemplazando proceso $pid >> logs/conn.log
    fi 
done

ip=`cat server_ip.txt`

if [ -z $ip ]
then
	echo $(date) - No hay IP >> logs/conn.log
	exit
fi

EPROM=$ip/eprom
files="ui.cfg|www/images/Logo_Custom.png|www/images/Salvapantalla.jpg"
files=(${files//|/ }) # Transformar en array

echo $(date) - Intentando conexión... >> logs/conn.log
ping -c 1 -q ${ip::-5} >> logs/conn.log 2>&1 # IP sin el puerto
while [ $? -ne 0 ]
do
	sleep 2
	ping -c 1 -q ${ip::-5}
done
echo $(date) - Conexión encontrada >> logs/conn.log

curl -I $ip # HEAD Request --> Verificar que existe el servidor
if [ $? -ne 0 ]
then
	echo $(date) - No se encontró el servidor en $ip. Abortando >> logs/conn.log
	exit # No cambiar la interfaz
fi
echo $(date) - Servidor encontrado, procediendo... >> logs/conn.log

for i in ${!files[@]}
do
	wget $EPROM/"${files[$i]}" -O ./"${files[$i]}" >> logs/conn.log 2>&1
done

./change_ui
